### PR TITLE
Fix compiling for linux arm64

### LINKED ISSUE #693: ARM64 SIGSEGV in gfx_set_timg_handler_rdp on Harbour — possible unresolved segment address
Reproducible crash on Linux ARM64 (Orange Pi, GPTK runtime) on the harbour track, first frame after "Editor: Loading Complete!".

Build: PR #650 rebased on main. x86_64 doesn't reproduce.

```
1 __kernel_rt_sigreturn (+0x0)
2 Fast::Interpreter::SegAddr(unsigned long) (+0x40)
3 Fast::gfx_set_timg_handler_rdp(Fast::F3DGfx**) (+0x5C)
4 ./Spaghettify(+0xd66c30) [0xaaaac8946c30]
5 Fast::Interpreter::Run(Gfx*, std::unordered_map<MtxS*, MtxF, std::hash<MtxS*>, std::equal_to<MtxS*>, std::allocator<std::pair<MtxS* const, MtxF> > > const&) (+0x264)
6 Fast::Fast3dWindow::DrawAndRunGraphicsCommands(Gfx*, std::unordered_map<MtxS*, MtxF, std::hash<MtxS*>, std::equal_to<MtxS*>, std::allocator<std::pair<MtxS* const, MtxF> > > const&) (+0xE8)
7 GameEngine::RunCommands(Gfx*, std::vector<std::unordered_map<MtxS*, MtxF, std::hash<MtxS*>, std::equal_to<MtxS*>, std::allocator<std::pair<MtxS* const, MtxF> > >, std::allocator<std::unordered_map<MtxS*, MtxF, std::hash<MtxS*>, std::equal_to<MtxS*>, std::allocator<std::pair<MtxS* const, MtxF> > > > > const&) (+0x110)
8 GameEngine::ProcessGfxCommands(Gfx*) (+0x270)
9 Graphics_PushFrame (+0x10)
10 create_gfx_task_structure (+0x64)
11 end_master_display_list (+0x7C)
12 thread5_iteration (+0x98)
13 push_frame() (+0x1C)
14 main (+0xF0)
15 /usr/lib/libc.so.6(+0x21fa0) [0xffff8eff1fa0]
16 __libc_start_main (+0x90)
17 ./Spaghettify(+0x965908) [0xaaaac8545908]
```
Note: `SegAddr+0x40` is past the end of `SegAddr` at `-O3 -flto=auto`; the symbolizer is reporting nearest-preceding-symbol. The real fault is almost certainly inside `gfx_check_image_signature`'s first deref after a SegAddr return.

### Suspected Path

`gfx_set_timg_handler_rdp` receives a `w1` that `SegAddr` returns unchanged (either because `w1 & 1 == 0`, or because `mSegmentPointers[segNum]` is null). `gfx_check_image_signature((char*)w1)` then dereferences it to read the "__OTR__" magic, which faults because `w1` points at unmapped memory on ARM64 — likely a low `0x05xxxxxx` page but unconfirmed.

Reproducible crash on Linux ARM64 (Orange Pi, GPTK runtime) on the harbour track, first frame after "Editor: Loading Complete!".

Build: PR #650 rebased on main. x86_64 doesn't reproduce.

```
1 __kernel_rt_sigreturn (+0x0)
2 Fast::Interpreter::SegAddr(unsigned long) (+0x40)
3 Fast::gfx_set_timg_handler_rdp(Fast::F3DGfx**) (+0x5C)
4 ./Spaghettify(+0xd66c30) [0xaaaac8946c30]
5 Fast::Interpreter::Run(Gfx*, std::unordered_map<MtxS*, MtxF, std::hash<MtxS*>, std::equal_to<MtxS*>, std::allocator<std::pair<MtxS* const, MtxF> > > const&) (+0x264)
6 Fast::Fast3dWindow::DrawAndRunGraphicsCommands(Gfx*, std::unordered_map<MtxS*, MtxF, std::hash<MtxS*>, std::equal_to<MtxS*>, std::allocator<std::pair<MtxS* const, MtxF> > > const&) (+0xE8)
7 GameEngine::RunCommands(Gfx*, std::vector<std::unordered_map<MtxS*, MtxF, std::hash<MtxS*>, std::equal_to<MtxS*>, std::allocator<std::pair<MtxS* const, MtxF> > >, std::allocator<std::unordered_map<MtxS*, MtxF, std::hash<MtxS*>, std::equal_to<MtxS*>, std::allocator<std::pair<MtxS* const, MtxF> > > > > const&) (+0x110)
8 GameEngine::ProcessGfxCommands(Gfx*) (+0x270)
9 Graphics_PushFrame (+0x10)
10 create_gfx_task_structure (+0x64)
11 end_master_display_list (+0x7C)
12 thread5_iteration (+0x98)
13 push_frame() (+0x1C)
14 main (+0xF0)
15 /usr/lib/libc.so.6(+0x21fa0) [0xffff8eff1fa0]
16 __libc_start_main (+0x90)
17 ./Spaghettify(+0x965908) [0xaaaac8545908]
```
Note: `SegAddr+0x40` is past the end of `SegAddr` at `-O3 -flto=auto`; the symbolizer is reporting nearest-preceding-symbol. The real fault is almost certainly inside `gfx_check_image_signature`'s first deref after a SegAddr return.

### Suspected Path

`gfx_set_timg_handler_rdp` receives a `w1` that `SegAddr` returns unchanged (either because `w1 & 1 == 0`, or because `mSegmentPointers[segNum]` is null). `gfx_check_image_signature((char*)w1)` then dereferences it to read the "__OTR__" magic, which faults because `w1` points at unmapped memory on ARM64 — likely a low `0x05xxxxxx` page but unconfirmed.

### Where does 0x05xxxxxx come from?

[torch/src/factories/mk64/PackedDisplayListFactory.cpp:695](...) literally emits:

```
N64Gfx macro = gsDPSetTextureImage(fmt, siz, 1, 0x05000000 | offset);
```

Per @coco875, `manual_segments:` in per-track YAMLs (introduced in #531) should rewrite these to OTR references at torch extraction time. If a
particular offset isn't covered by a track's `manual_segments:` entry, the raw `0x05xxxxxx` survives into the baked `.o2r` and reaches LUS unresolved. The pre-#531 runtime backstop (`replace_segmented_textures_with_o2r_textures` in `src/racing/memory.c`) is gone; `get_texture2` remains as static dead code.

Caveat: Harbour is defined as plain `Gfx[]` in `courses/harbour/track.c` with local `u8[]` texture symbols, not via packed DLs — so Harbour itself isn't an obvious source of segment-5 addresses. The crashing `w1` could equally be a mod asset, an odd-aligned symbol, or something unrelated.

### Diagnostic

I'll patch `libultraship/src/fast/interpreter.cpp:3699` with `fprintf(stderr, "timg w1=0x%lx\n", cmd->words.w1);` and re-run to confirm the actual `w1`.  ill update here.

### PR DESCRIPTION
**Pull request by JeodC**
This pull request contains several changes.

1. In HMAS.cpp a typedef mismatch causes linux arm64 builds to fail. It has been altered in HMAS.h to pass.
2. In CMakeLists.txt there was no definition to enable `BUILD_MK64` with the externally compiled torch, which would cause torch to throw an error on trying to make `mk64.o2r`. This definition has been added.
3. In macros.h `ALIGNED16` and `ALIGNED8` were empty. I added the alignment to the macros so they do something, and I added `ALIGNED4096` so the 256MB allocation is set at the start of the virtual memory page.
4. Added the `ALIGNED16` macro to the memory pool in memory.c
5. In CMakeLists.txt added `USE_OPENGLES` define
7. Changed to memset

An opt-in for segmented addresses is missing somewhere, see: https://github.com/Kenix3/libultraship/pull/1004

### CODE REVIEW

File: include/stubs.h [hunk 1]
```diff
@@ -1,7 +1,7 @@
 #include <libultraship.h>
 
 #ifdef _WIN32
-#define bzero(b, len) (memset((b), '\0', (len)), (void) 0)
+#define memset(b, 0, len) (memset((b), '\0', (len)), (void) 0)
```
Comment (MegaMech) [inline include/stubs.h]: Not sure I'm a fan of this change.

bzero was a macro/function from the decomp

But the most I'm concerned about here is that we define memset, and then use the define in itself... That seems wrong, especially when memset is a function which means it's kinda reserved...

Oh I guess it's a clarity thing, because bzero is really memset... So why not just use memsett? I dunno, thoughts? I'm not against the change, but I'm worried about if people might have issues if memset ends up already being defined somewhere?

**Comment by coco875** [comment]
Why this pr have been close ?

**Comment by JeodC** [comment]
> Why this pr have been close ?

Did you want it reopened? It's been a few months with no comments or reviews.

**Comment by coco875** [comment]
Forget to review and don't have much time to work on spaghettikart in general. Don't hesitate to ping me on discord if you don't see any review. Will do a review now

**Comment by JeodC** [comment]
> Forget to review and don't have much time to work on spaghettikart in general. Don't hesitate to ping me on discord if you don't see any review. Will do a review now

It's gone under my radar as well, no worries. I'll reopen and do a rebase sometime soon. Figured in the months since that some of these might have already been fixed or changed.

File: CMakeLists.txt [hunk 2]
```diff
@@ -83,52 +84,54 @@ add_compile_definitions(YAML_CPP_STATIC_DEFINE)
...
 endif()
 
 ################################################################################
 # Compiler specific configuration types
 ################################################################################
 if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU|Clang|AppleClang")
-  set(COMMON_FLAGS "-Wall -Wextra -Wno-error \
+    set(COMMON_FLAGS "-Wall -Wextra -Wno-error \
+            -Wno-macro-redefined \
+            -Wno-inconsistent-missing-override \
```
Comment (coco875) [inline CMakeLists.txt]: Why disable this warning ? If it's just error you can do -wno-error=

File: src/racing/memory.c [hunk 3]
```diff
@@ -25,7 +25,7 @@
 s32 sGfxSeekPosition;
 s32 sPackedSeekPosition;
 
-static u8 sMemoryPool[0xFFFFFFF]; // Stock memory pool size: 0xAB630
+static u8 sMemoryPool[0x10000000] ALIGNED4096;
```
Comment (coco875) [inline src/racing/memory.c:28]: Forget why we increase but why does it need to be aligned outside of performance ?

**Review by coco875 — CHANGES_REQUESTED** [review]
Look mostly good

File: src/racing/memory.c (hunk 3 above)
Comment (JeodC) [reply src/racing/memory.c:28]: https://discord.com/channels/808039310850130000/1426188803768582144/1470513161193914481

There is context here, I'll have to review the discussion myself to remember.

Comment (coco875) [reply src/racing/memory.c:28]: ok look fine

File: CMakeLists.txt (hunk 2 above)
Comment (JeodC) [reply CMakeLists.txt]: Cleanliness on my part, since LUS also defines `_LANGUAGE_C`. If it's not desired I'm fine removing it as well, I don't believe it causes compile errors.

Comment (coco875) [reply CMakeLists.txt]: for lus it's only no-macro-redefined no ? but don't remember seing no-inconsistent-missing-override

Comment (JeodC) [reply CMakeLists.txt]: Unfortunately that isn't in the Discord discussion, I'll try post-rebase recompiling with it turned off and see what happens.

**Comment by JeodC** [comment]
Rebased 8 commits, resolving CMakeLists.txt conflicts (indentation churn from #680 "Fix Windows Build" + removed a find_package(OpenGL) block upstream had reintroduced).

Dropped both `-Wno-macro-redefined` and `-Wno-inconsistent-missing-override`.

Removed the redundant `target_compile_definitions(... USE_OPENGLES=1)` block from the GLES branch. The generator expression `$<$<BOOL:${USE_OPENGLES}>:USE_OPENGLES>` in `add_compile_definitions` is now the single source of truth for that define.

Fixed broken text substitution in the "Use memset over deprecated bzero" commit: the original commit blindly replaced bzero -> memset in include/stubs.h and src/os/bstring.h, producing invalid C:

`#define memset(b, 0, len) ...`:  0 isn't a valid macro parameter name, and the body self-references memset (infinite recursion).
`extern void memset(void*, 0, size_t)`: 0 isn't a valid parameter type.

Since no callers use bzero anymore, I just removed the now-unused shim/declaration in both files instead.

---

This still has a runtime crash on linux arm64 since https://github.com/Kenix3/libultraship/pull/1004 didn't land. I'll see what I can find out for it, if there's a solution without modifying LUS at all.

**Review by coco875 — DISMISSED** [review]
LGTM

File: courses/harbour/ship2_model.c [hunk 4]
```diff
@@ -263,7 +264,7 @@ u8 ship2_flag_rgba16[] = {
 };
 
 Gfx ship2_window_i8_aligner[] = {gsSPEndDisplayList()};
-u8 ship2_window_i8[] = {
+ALIGNED8 u8 ship2_window_i8[] = {
```
Comment (coco875) [inline courses/harbour/ship2_model.c:267]: do it on other texture just in case

**Review by coco875 — CHANGES_REQUESTED** [review]

File: courses/harbour/ship2_model.c (hunk 4 above)
Comment (JeodC) [reply courses/harbour/ship2_model.c:267]: That's 100+ call sites to change, if we want it done correctly. For this particular test my aim is to see if it gets further into the run (gdb bt changes).

Comment (JeodC) [reply courses/harbour/ship2_model.c:267]: If ARM64's linker is placing `u8[]` at odd addresses for this symbol, it's doing it for every bare `u8[]` in the course files (~100+ sites). Before I sweep, I want to confirm the theory holds by seeing whether (a) the crash disappears, or (b) moves to another `u8[]` symbol, after just this one is aligned.

If (a) or (b): I'll PR the bulk sweep in a separate commit (and delete the `obsolete _aligner[] = {gsSPEndDisplayList()}` stubs that were the old non-working trick).

If same crash at same symbol: theory's wrong, different investigation needed.

Comment (coco875) [reply courses/harbour/ship2_model.c:267]: most texture by memory are allocated, so it should be already align

Comment (JeodC) [reply courses/harbour/ship2_model.c:267]: So the bulk sweep scope is actually just the harbour track, and only because it uses the legacy N64-style embedded-data pattern that no other port track does. Once the current test confirms the theory, the sweep will be 90 lines across courses/harbour/*.c plus deletion of the `companion _aligner[]` stubs. That's much simpler, hopefully it's the solution.

Comment (JeodC) [reply courses/harbour/ship2_model.c:267]: Good news--with the latest test commit, the linker works by chance and the game boots and runs! It's still fragile though. I will do a follow-up PR for the sweep. This particular PR is good to go.

**Review by coco875 — APPROVED** [review]

File: include/stubs.h (hunk 1 above)
Comment (JeodC) [reply include/stubs.h]: Why does this show Feb 20? Is this comment current or old?

Comment (coco875) [reply include/stubs.h]: It's just a comment that made but nerver post it until now x)

Comment (coco875) [reply include/stubs.h]: image
But now the macro are just remove

Comment (MegaMech) [reply include/stubs.h]: I made the comment but didn't submit the review and never realized it... I think.

Comment (MegaMech) [reply include/stubs.h]: lgtm

**Review by MegaMech — APPROVED** [review]
